************************************************************************
* id: 468
* requirement: Fix test that catches AssertionError
*=======================================================================
* no changes, only the initial requirement, implements, and discussion.
*=======================================================================
************************************************************************
* type: implements
*-----------------------------------------------------------------------
* time: 2016-11-22T03:37:54Z
* content: Fix test that catches AssertionError
* codeUrl: github.com/JetBrains/intellij-community/pull/468/commits/5414416a0c321c245df7ca1468da92aac7f3abdd
************************************************************************
************************************************************************
* type: discussion
*-----------------------------------------------------------------------
* time: 2016-11-22T03:41:29Z
* content: â€¦ from its own call to TestCase.fail.
* time: 2016-11-22T03:50:20Z
* content: This follows up commit cd7477b by cdr@jetbrains.com.
************************************************************************
